import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./grid.css";

import "../icon/fontawesome/css/all.min.css";
import { Providers } from "@/lib/Providers";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import Modal from "react-modal";
import HeaderWrapper from "@/components/header/wrapHeader";
import Header from "@/components/header/Header";
import HeaderLogged from "@/components/header/Headerlogged";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <HeaderWrapper />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              duration: 2000,
            }}
          />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
