import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./grid.css";
import "./globals.css";
import "../icon/fontawesome/css/all.min.css";
import { Providers } from "@/lib/Providers";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import Modal from "react-modal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <Header />
        <Toaster position="top-center" reverseOrder={false} toastOptions={{
          duration: 2000,
        }}/>
        <Providers> {children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
